name: Build and Test
on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"
      - ".editorconfig"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # Note: all combinations of the following will be run independently
        os: [macos-15, ubuntu-24.04, windows-2025]
        swift: ["6.2.4"]
        config: [release, debug]

        include:
          # Disable exporting code coverage by default.
          - export-coverage: false

          # Enable exporting code coverage in a single configuration.
          - os: "ubuntu-24.04"
            config: debug
            export-coverage: true

          - config: release
            llvm-build-type: MinSizeRel

          - config: debug
            llvm-build-type: Debug

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Swift ${{ matrix.swift }} on ${{ matrix.os }}
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift }}

      - name: Download Recent Visual Studio and Windows SDK
        uses: compnerd/gha-setup-vsdevenv@main
        with:
          winsdk: "10.0.26100.0"
          # Note: The GitHub windows-2025 runner has only a very old version of the Windows SDK available by default.
          #       Swift is said to require version 10.0.22621.0: https://forums.swift.org/t/swiftpm-plugin-doesnt-work-with-the-latest-visual-studio-version/78183/14
          #       That no longer works, so we had to upgrade to 10.0.26100.0.
          #       See also: https://github.com/swiftlang/swift/issues/88237

      - name: Verify swift version
        run: swift --version && swift --version | grep -q ${{ matrix.swift }}
        shell: bash

      - name: Set up LLVM
        uses: hylo-lang/get-llvm@v0.3.0
        id: get-llvm
        with:
          llvmVersion: "20.1.6"
          llvmBuildRelease: "20260309-221030"
          llvmBuildConfig: ${{ matrix.llvm-build-type }}
          addToPkgConfigPath: true
          addToPath: true

      # We disabled the separate build step, as it consumes extra CI time - building for testing apparently doesn't
      # reuse the build cache from here, doubling the CI time.

      - name: Build and test for ${{ matrix.swift }} on ${{ matrix.os }} in ${{ matrix.config }} mode
        run: swift test -c ${{ matrix.config }} --verbose ${{ matrix.export-coverage && '--enable-code-coverage' || '' }}

      - name: Export code coverage
        if: ${{ matrix.export-coverage }}
        run: llvm-cov export $(swift build --show-bin-path)/HyloPackageTests.xctest  --format="lcov" --instr-profile $(swift build --show-bin-path)/codecov/default.profdata > info.lcov

      - name: Upload coverage report to Codecov
        if: ${{ matrix.export-coverage }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

    runs-on: ${{ matrix.os }}
